spring.application.name=SGS

# Configuracoes de Banco de Dados Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/sgs_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracoes JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Desliga a criação automática do Hibernate (O Flyway assume isso agora)
spring.jpa.hibernate.ddl-auto=validate


# Ativa o Flyway
spring.flyway.enabled=true


