spring.application.name=SGS

# Configuracoes de Banco de Dados Postgres
spring.datasource.url=jdbc:postgresql://172.19.142.217:5432
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=senha123

# Configuracoes JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Nao gerar DDL automaticamente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Executar scripts DDL e DML na inicializacao
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

